<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<c:set var="path" value="${pageContext.request.contextPath}" />
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
<link rel="stylesheet" href="${path}/css/magazine/magazineList-style.css"/>
<script type="text/javascript" src="${path}/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
 	$().ready(function(){
 		$("#mag_cate_name1").on("click", function(){
 			location.href = "${path}/magazine/list/2";
 		});
 		$("#mag_cate_name2").on("click", function(){
 			location.href = "${path}/magazine/list/3";
 		});
 		$("#mag_cate_name3").on("click", function(){
 			location.href = "${path}/magazine/list/4";
 		});
 		$("#mag_cate_name4").on("click", function(){
 			location.href = "${path}/magazine/list/5";
 		});
 		$("#mag_cate_name5").on("click", function(){
 			location.href = "${path}/magazine/list/6";
 		});
 		$("#mag_cate_name6").on("click", function(){
 			location.href = "${path}/magazine/list/7";
 		});
/* 		var 
		$(".like_btn").on("click", function(){
			$.post('${path}/view/mmaUpdateLikeCount'){
				
			}
		}); */
	});
</script>
</head>
<body>
<jsp:include page="/WEB-INF/view/header.jsp" />




<div id="cont_wrap" class="clfix" style="margin: 0px auto; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 12px; line-height: inherit; font-family: 돋움, Dotum, '맑은 고딕', 'Malgun Gothic', 'Apple Gothic', sans-serif; vertical-align: baseline; zoom: 1; background-image: initial; background-position: 0px center; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: #666666;">
<div id="conts_section" class="my_fold" style="margin: 0px auto; padding: 0px 20px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; width: 1008px;">
<div id="conts" style="margin: 0px; padding: 52px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; z-index: 10; width: 1008px; min-height: 800px; zoom: 1;">
<div class="ms_wrap_cont" style="margin: 0px; padding: 0px 0px 88px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 1008px; position: relative;">
<h2 class="ms_tit" style="padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; margin: 0px !important 0px 0px 0px;"><span class="music_today" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top; display: inline-block; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bg_h2_title_160712.png') 0px -106px repeat-y; width: 111px; height: 22px;">뮤직 스토리</span></h2>
<div id="d_wrap_tab_music" class="wrap_tab_music on" style="margin: 11px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative;">
<div class="wrap_tab03 type02" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; background-color: #ebf0ed;">
<ul style="margin: 0px; padding: 0px; border-width: 2px 0px 1px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; position: relative; width: 1008px; border-color: #848484 initial #dbdbdb initial; border-style: solid initial solid initial;">
</ul>
</div>
<div id="d_gnr_list1" class="gnr_list" style="margin: 0px; padding: 0px; border-top: 1px solid #b9b9b9; border-right: 0px; border-bottom: 1px solid #b9b9b9; border-left: 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 1008px; overflow: hidden; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_tab_gnr.png') repeat;">
<ul style="margin: 0px 0px -1px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: top; list-style: none; width: 1058.39px; display: inline-block; overflow: hidden;">
<li style="margin: 0px 0px 0px -1px; padding: 0px 9px 0px 13px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; float: left; width: 151px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_gnr_list2.png') 0px 10px no-repeat;"><a id="mag_cate_name1" class="mag_cate_name" href="javascript:void(0)" style="margin: 0px; padding: 7px 0px 6px 12px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; color: #333333; display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 145px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_btn_icon_arrow.png') 0px 13px no-repeat;">전체</a></li>
<li style="margin: 0px 0px 0px -1px; padding: 0px 9px 0px 13px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; float: left; width: 151px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_gnr_list2.png') 0px 10px no-repeat;"><a id="mag_cate_name2" class="mag_cate_name" href="javascript:void(0)" style="margin: 0px; padding: 7px 0px 6px 12px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; color: #333333; display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 145px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_btn_icon_arrow.png') 0px 13px no-repeat;">2017 MMA 결산특집</a></li>
<li style="margin: 0px 0px 0px -1px; padding: 0px 9px 0px 13px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; float: left; width: 151px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_gnr_list2.png') 0px 10px no-repeat;"><a id="mag_cate_name3" class="mag_cate_name" href="javascript:void(0)" style="margin: 0px; padding: 7px 0px 6px 12px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; color: #333333; display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 145px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_btn_icon_arrow.png') 0px 13px no-repeat;">금주의 신보</a></li>
<li style="margin: 0px 0px 0px -1px; padding: 0px 9px 0px 13px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; float: left; width: 151px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_gnr_list2.png') 0px 10px no-repeat;"><a id="mag_cate_name4" class="mag_cate_name" href="javascript:void(0)" style="margin: 0px; padding: 7px 0px 6px 12px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; color: #333333; display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 145px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_btn_icon_arrow.png') 0px 13px no-repeat;">금주의 차트</a></li>
<li style="margin: 0px 0px 0px -1px; padding: 0px 9px 0px 13px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; float: left; width: 151px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_gnr_list2.png') 0px 10px no-repeat;"><a id="mag_cate_name5" class="mag_cate_name" href="javascript:void(0)" style="margin: 0px; padding: 7px 0px 6px 12px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; color: #333333; display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 145px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_btn_icon_arrow.png') 0px 13px no-repeat;">아티스트 갤러리</a></li>
<li style="margin: 0px 0px 0px -1px; padding: 0px 9px 0px 13px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; float: left; width: 151px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_gnr_list2.png') 0px 10px no-repeat;"><a id="mag_cate_name6" class="mag_cate_name" href="javascript:void(0)" style="margin: 0px; padding: 7px 0px 6px 12px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; color: #333333; display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 145px; background: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_btn_icon_arrow.png') 0px 13px no-repeat;">이슈 포커스</a></li>
</ul>
</div>
<h3 class="ms_tit" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span class="music_today_story" style="margin: 29px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top; display: inline-block; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bg_h2_title_160712.png') 0px -135px repeat-y; width: 370px; height: 17px;">오늘의 스토리 매일의 뮤직스토리를 한눈에 모아보세요</span></h3>
<div class="recnt_musictoday" style="margin: 8px 0px 0px; padding: 24px 0px 20px; border: 8px solid #ededed; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<div class="musicspecl_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: top; position: relative; width: 992px; display: inline-block;">
<div class="list_date" style="margin: 0px; padding: 8px 18px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 109px; text-align: center;"><span class="today" style="margin: 0px; padding: 0px 0px 13px 5px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/web/musicstory/img_today.png" alt="TODAY" width="58" height="58" /></span><span class="wrap_number_big" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 17px; display: block;">&nbsp;</span><span class="wrap_number_small" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 9px; display: inline-block;"><span class="text" style="margin: 0px -4px 0px 0px; padding: 0px; border: 0px; font-stretch: normal; line-height: 18px; font-family: arial, dotum; vertical-align: middle; background: 0px center; width: auto; height: auto; display: inline-block;">2017.10</span></span></div>
<p class="image" style="margin: 0px 24px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; float: left; width: 240px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="[이슈 포커스] 다중음격 172회: 대규모 그룹이 성황을 이루기까지 Pt. 1 [한동윤] "><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171025051250996.jpg" alt="휴식이 절실히 필요한 이때!" width="240" height="135" /></a></p>
<dl style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 592px; float: left;">
<dt style="margin: 0px 0px -3px -1px; padding: 5px 0px 13px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: 26px; font-family: '맑은 고딕', 'Malgun Gothic', 돋움, Dotum, 'Apple Gothic', sans-serif; vertical-align: baseline; overflow: hidden; color: #1a1a1a; width: 592px; white-space: nowrap; text-overflow: ellipsis; letter-spacing: -1px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="[이슈 포커스]">[이슈 포커스]</a>&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="다중음격 172회: 대규모 그룹이 성황을 이루기까지 Pt. 1 [한동윤]">다중음격 172회: 대규모 그룹이 성황을 이루기까지 Pt. 1 [한동윤]</a></dt>
<dd class="sumry" style="margin: 0px 32px 10px 1px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline; min-height: 60px; word-wrap: break-word; word-break: break-all;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="다섯은 평균이 됐다. 예닐곱도 예사다. 이제는 그 이상의 숫자로 구성된 아이돌 그룹이 꾸준히 증가하는 추세다. 세븐틴, 업텐션, 우주소녀, 펜타곤, 바시티, 프리스틴, 굿데이, 골든차일드, TRCNG처럼 열 명 이상의 멤버를 꾸린 팀도 많다. 얼마 뒤에는 12인조 보이 밴드 더보이즈도 데뷔한다. 대가족 그룹은 트렌드나 다름없다.">다섯은 평균이 됐다. 예닐곱도 예사다. 이제는 그 이상의 숫자로 구성된 아이돌 그룹이 꾸준히 증가하는 추세다. 세븐틴, 업텐션, 우주소녀, 펜타곤, 바시티, 프리스틴, 굿데이, 골든차일드, TRCNG처럼 열 명 이상의 멤버를 꾸린 팀도 많다. 얼마 뒤에는 12인조 보이 밴드 더보이즈도 데뷔한...</a></dd>
<dd class="like_btn" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: right; width: 592px; display: inline-block;">
<p class="left" style="margin: 0px; padding: 3px 0px 0px 1px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; text-align: left;"><span class="colk1_like" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.2em; font-family: 돋움, dotum, 'Apple Gothic', sans-serif; vertical-align: middle;">2</span>&nbsp;<span class="cnt_cmt" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">댓글</span>&nbsp;1</span>&nbsp;<span class="cnt_view" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">조회</span>&nbsp;182</span></p>
</dd>
</dl>
</div>
</div>
<div class="wrap_musicspecl list_type01 line_top" style="margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; border-color: #cccccc initial initial initial; border-style: solid initial initial initial;">
<ul style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none;">
<li style="margin: 0px; padding: 16px 0px; border-width: 0px 0px 1px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: initial initial #e6e6e6 initial; border-style: initial initial solid initial;">
<div class="musicspecl_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: top; position: relative; width: 1008px; display: inline-block;">
<div class="list_date" style="margin: 0px; padding: 48px 10px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 125px; text-align: center;"><span class="wrap_number_big" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 17px; display: block;">&nbsp;</span><span class="wrap_number_small" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 9px; display: inline-block;"><span class="text" style="margin: 0px -4px 0px 0px; padding: 0px; border: 0px; font-stretch: normal; line-height: 18px; font-family: arial, dotum; vertical-align: middle; background: 0px center; width: auto; height: auto; display: inline-block;">2017.10</span></span></div>
<p class="image" style="margin: 0px 22px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; float: left; width: 240px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="95회: Tom Petty의 위대한 유산 Pt. 2 [박효재] - 페이지 이동"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171025025537471.jpg" alt="95회: Tom Petty의 위대한 유산 Pt. 2 [박효재]" width="240" height="135" /></a></p>
<dl style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 610px; float: left;">
<dt style="margin: 0px 0px -3px -1px; padding: 15px 0px 7px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; color: #1a1a1a; width: 610px; white-space: nowrap; text-overflow: ellipsis; height: 22px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="스쿨 오브 록 - 페이지 이동">[스쿨 오브 록]</a>&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="95회: Tom Petty의 위대한 유산 Pt. 2 [박효재] - 페이지 이동">95회: Tom Petty의 위대한 유산 Pt. 2 [박효재]</a></dt>
<dd class="sumry" style="margin: 0px 32px 16px 1px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline; min-height: 44px; word-wrap: break-word; word-break: break-all;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="1979년 Tom Petty의 29번째 생일 전날인 10월19일 발매된 3집 [Damn the Torpedoes]는 스스로에게 준 선물이었다. 이 앨범으로 Petty와 그의 밴드는 확실히 유명해졌다. 빌보드 앨범차트 2위까지 올랐고 300만장 넘게 팔렸다. 수록곡 'Don't Do Me Like That'과 'Refugee'는 각각 싱글차트 10위, 15위까지 랭크됐다. 처음으로 록스타다운 스타덤을 만끽했다. - 페이지 이동">1979년 Tom Petty의 29번째 생일 전날인 10월19일 발매된 3집 [Damn the Torpedoes]는 스스로에게 준 선물이었다. 이 앨범으로 Petty와 그의 밴드는 확실히 유명해졌다. 빌보드 앨범차트 2위까지 올랐고 300만장..</a></dd>
<dd class="like_btn" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: right; width: 610px; display: inline-block;">
<p class="left" style="margin: 0px; padding: 3px 0px 0px 1px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; text-align: left;"><span class="colk1_like" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.2em; font-family: 돋움, dotum, 'Apple Gothic', sans-serif; vertical-align: middle;">1</span>&nbsp;<span class="cnt_cmt" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">댓글</span>&nbsp;1</span>&nbsp;<span class="cnt_view" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">조회</span>&nbsp;133</span></p>
</dd>
</dl>
</div>
</li>
<li style="margin: 0px; padding: 16px 0px; border-width: 0px 0px 1px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: initial initial #e6e6e6 initial; border-style: initial initial solid initial;">
<div class="musicspecl_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: top; position: relative; width: 1008px; display: inline-block;">
<div class="list_date" style="margin: 0px; padding: 48px 10px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 125px; text-align: center;"><span class="wrap_number_big" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 17px; display: block;">&nbsp;</span><span class="wrap_number_small" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 9px; display: inline-block;"><span class="text" style="margin: 0px -4px 0px 0px; padding: 0px; border: 0px; font-stretch: normal; line-height: 18px; font-family: arial, dotum; vertical-align: middle; background: 0px center; width: auto; height: auto; display: inline-block;">2017.10</span></span></div>
<p class="image" style="margin: 0px 22px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; float: left; width: 240px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="새로운 전설을 만들어가는 뮤지션, Ed Sheeran [한지훈] - 페이지 이동"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171025121642833.jpg" alt="새로운 전설을 만들어가는 뮤지션, Ed Sheeran [한지훈]" width="240" height="135" /></a></p>
<dl style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 610px; float: left;">
<dt style="margin: 0px 0px -3px -1px; padding: 15px 0px 7px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; color: #1a1a1a; width: 610px; white-space: nowrap; text-overflow: ellipsis; height: 22px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="Hi-Fi 가이드 - 페이지 이동">[Hi-Fi 가이드]</a>&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="새로운 전설을 만들어가는 뮤지션, Ed Sheeran [한지훈] - 페이지 이동">새로운 전설을 만들어가는 뮤지션, Ed Sheeran [한지훈]</a></dt>
<dd class="sumry" style="margin: 0px 32px 16px 1px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline; min-height: 44px; word-wrap: break-word; word-break: break-all;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="The Beatles를 필두로 Michael Jackson, The Rolling Stones, Queen, Pink Floyd, Metallica, U2, Adele의 공통점이 뭐가 있을까요? 일단 시대와 장르를 대표하는 뮤지션이라는 데에는 그 누구도 이의를 제기하지 못할 것이고요. 이제부터 어려워집니다. 영국 출신인가 하고 보니 Michael Jackson에서부터 걸리고, 성별, 인종 모두 다릅니다. 하지만 이들에게는 웸블리 스타디움에서 공연을 했다는 공통점이 있습니다. 이 중에서도 Queen의 1986년 웸블리 스타디움 공연은 록 음악 역사 상, 아니 20세기 대중음악의 역사 상 최고의 라이브 공연으로 꼽아도 손색이 없을 공연이죠. - 페이지 이동">The Beatles를 필두로 Michael Jackson, The Rolling Stones, Queen, Pink Floyd, Metallica, U2, Adele의 공통점이 뭐가 있을까요? 일단 시대와 장르를 대표하는 뮤지션이라는 데에는 그 누구도 이의를 제기하..</a></dd>
<dd class="like_btn" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: right; width: 610px; display: inline-block;">
<p class="left" style="margin: 0px; padding: 3px 0px 0px 1px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; text-align: left;"><span class="colk1_like" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.2em; font-family: 돋움, dotum, 'Apple Gothic', sans-serif; vertical-align: middle;">49</span>&nbsp;<span class="cnt_cmt" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">댓글</span>&nbsp;0</span>&nbsp;<span class="cnt_view" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">조회</span>&nbsp;1,249</span></p>
</dd>
</dl>
</div>
</li>
<li style="margin: 0px; padding: 16px 0px; border-width: 0px 0px 1px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: initial initial #e6e6e6 initial; border-style: initial initial solid initial;">
<div class="musicspecl_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: top; position: relative; width: 1008px; display: inline-block;">
<div class="list_date" style="margin: 0px; padding: 48px 10px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 125px; text-align: center;"><span class="wrap_number_big" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 17px; display: block;">&nbsp;</span><span class="wrap_number_small" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 9px; display: inline-block;"><span class="text" style="margin: 0px -4px 0px 0px; padding: 0px; border: 0px; font-stretch: normal; line-height: 18px; font-family: arial, dotum; vertical-align: middle; background: 0px center; width: auto; height: auto; display: inline-block;">2017.10</span></span></div>
<p class="image" style="margin: 0px 22px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; float: left; width: 240px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="캡틴락과 슈퍼세션의 다시 쓰는 프로필 [캡틴락] 작업기 - 페이지 이동"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171025104650844.jpg" alt="캡틴락과 슈퍼세션의 다시 쓰는 프로필 [캡틴락] 작업기" width="240" height="135" /></a></p>
<dl style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 610px; float: left;">
<dt style="margin: 0px 0px -3px -1px; padding: 15px 0px 7px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; color: #1a1a1a; width: 610px; white-space: nowrap; text-overflow: ellipsis; height: 22px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="아티스트 갤러리 - 페이지 이동">[아티스트 갤러리]</a>&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="캡틴락과 슈퍼세션의 다시 쓰는 프로필 [캡틴락] 작업기 - 페이지 이동">캡틴락과 슈퍼세션의 다시 쓰는 프로필 [캡틴락] 작업기</a></dt>
<dd class="sumry" style="margin: 0px 32px 16px 1px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline; min-height: 44px; word-wrap: break-word; word-break: break-all;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="캡틴락 앨범에 참여한 훌륭한 뮤지션들을 소개합니다! 크라잉넛의 베이시스트 한경록이 데뷔 22년만에 처음으로 캡틴락이라는 이름으로 데뷔 22년만에 첫 번째 솔로 정규앨범을 발매했다. &quot;나 자신에 대해 표현하고 싶었다&quot;고 솔로 앨범 발매에 대한 출사표를 던진 캡틴락은 과연 그동안 보여주었던 음악들과는 조금 차별화된, 그리고 조금 더 솔직하게 자기의 이야기들을 노래한 곡들을 앨범에 빼곡히 수록했다. - 페이지 이동">캡틴락 앨범에 참여한 훌륭한 뮤지션들을 소개합니다! 크라잉넛의 베이시스트 한경록이 데뷔 22년만에 처음으로 캡틴락이라는 이름으로 데뷔 22년만에 첫 번째 솔로 정규앨범을 발매했다. "나 자신에 대해 표현..</a></dd>
<dd class="like_btn" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: right; width: 610px; display: inline-block;">
<p class="left" style="margin: 0px; padding: 3px 0px 0px 1px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; text-align: left;"><span class="colk1_like" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.2em; font-family: 돋움, dotum, 'Apple Gothic', sans-serif; vertical-align: middle;">9</span>&nbsp;<span class="cnt_cmt" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">댓글</span>&nbsp;16</span>&nbsp;<span class="cnt_view" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">조회</span>&nbsp;646</span></p>
</dd>
</dl>
</div>
</li>
<li style="margin: 0px; padding: 16px 0px; border-width: 0px 0px 1px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: initial initial #e6e6e6 initial; border-style: initial initial solid initial;">
<div class="musicspecl_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: top; position: relative; width: 1008px; display: inline-block;">
<div class="list_date" style="margin: 0px; padding: 48px 10px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 125px; text-align: center;"><span class="wrap_number_big" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 17px; display: block;">&nbsp;</span><span class="wrap_number_small" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 9px; display: inline-block;"><span class="text" style="margin: 0px -4px 0px 0px; padding: 0px; border: 0px; font-stretch: normal; line-height: 18px; font-family: arial, dotum; vertical-align: middle; background: 0px center; width: auto; height: auto; display: inline-block;">2017.10</span></span></div>
<p class="image" style="margin: 0px 22px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; float: left; width: 240px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="이예준의 감성이 함께 한 가을 발라드 '진심' - 페이지 이동"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171025115126012.jpg" alt="이예준의 감성이 함께 한 가을 발라드 '진심'" width="240" height="135" /></a></p>
<dl style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 610px; float: left;">
<dt style="margin: 0px 0px -3px -1px; padding: 15px 0px 7px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; color: #1a1a1a; width: 610px; white-space: nowrap; text-overflow: ellipsis; height: 22px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="아티스트 갤러리 - 페이지 이동">[아티스트 갤러리]</a>&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="이예준의 감성이 함께 한 가을 발라드 '진심' - 페이지 이동">이예준의 감성이 함께 한 가을 발라드 '진심'</a></dt>
<dd class="sumry" style="margin: 0px 32px 16px 1px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline; min-height: 44px; word-wrap: break-word; word-break: break-all;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="보컬리스트 이예준이 '진심'을 들고 찾아왔습니다. 쓸쓸한 가을바람 소리와도 너무나도 닮아있는 발라드 '진심'을 발매합니다. 10월 25일 발매되는 이예준의 디지털 싱글의 미공개 포토를 멜론에서 단독으로 공개합니다. - 페이지 이동">보컬리스트 이예준이 '진심'을 들고 찾아왔습니다. 쓸쓸한 가을바람 소리와도 너무나도 닮아있는 발라드 '진심'을 발매합니다. 10월 25일 발매되는 이예준의 디지털 싱글의 미공개 포토를 멜론에서 단독으로 공..</a></dd>
<dd class="like_btn" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: right; width: 610px; display: inline-block;">
<p class="left" style="margin: 0px; padding: 3px 0px 0px 1px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; text-align: left;"><span class="colk1_like" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.2em; font-family: 돋움, dotum, 'Apple Gothic', sans-serif; vertical-align: middle;">24</span>&nbsp;<span class="cnt_cmt" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">댓글</span>&nbsp;42</span>&nbsp;<span class="cnt_view" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">조회</span>&nbsp;604</span></p>
</dd>
</dl>
</div>
</li>
<li style="margin: 0px; padding: 16px 0px; border-width: 0px 0px 1px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: initial initial #e6e6e6 initial; border-style: initial initial solid initial;">
<div class="musicspecl_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: top; position: relative; width: 1008px; display: inline-block;">
<div class="list_date" style="margin: 0px; padding: 48px 10px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 125px; text-align: center;"><span class="wrap_number_big" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 17px; display: block;">&nbsp;</span><span class="wrap_number_small" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; height: 9px; display: inline-block;"><span class="text" style="margin: 0px -4px 0px 0px; padding: 0px; border: 0px; font-stretch: normal; line-height: 18px; font-family: arial, dotum; vertical-align: middle; background: 0px center; width: auto; height: auto; display: inline-block;">2017.10</span></span></div>
<p class="image" style="margin: 0px 22px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; float: left; width: 240px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="상큼발랄 고막여친 혜이니 '콩깍지' MV 촬영 현장 비하인드 - 페이지 이동"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171024103525590.jpg" alt="상큼발랄 고막여친 혜이니 '콩깍지' MV 촬영 현장 비하인드" width="240" height="135" /></a></p>
<dl style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 610px; float: left;">
<dt style="margin: 0px 0px -3px -1px; padding: 15px 0px 7px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; color: #1a1a1a; width: 610px; white-space: nowrap; text-overflow: ellipsis; height: 22px;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="아티스트 갤러리 - 페이지 이동">[아티스트 갤러리]</a>&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="상큼발랄 고막여친 혜이니 '콩깍지' MV 촬영 현장 비하인드 - 페이지 이동">상큼발랄 고막여친 혜이니 '콩깍지' MV 촬영 현장 비하인드</a></dt>
<dd class="sumry" style="margin: 0px 32px 16px 1px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline; min-height: 44px; word-wrap: break-word; word-break: break-all;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;" title="한 번 들으면 잊을 수 없는, 독보적인 음색의 소유자 혜이니 (HEYNE)가 1년여 만의 여섯 번째 디지털 싱글 '콩깍지(Love is Blind)'로 돌아왔습니다. 상큼 발랄한 혜이니의 '콩깍지' 뮤직비디오 촬영현장을 멜론 가족 여러분께 단독으로 공개합니다. - 페이지 이동">한 번 들으면 잊을 수 없는, 독보적인 음색의 소유자 혜이니 (HEYNE)가 1년여 만의 여섯 번째 디지털 싱글 '콩깍지(Love is Blind)'로 돌아왔습니다. 상큼 발랄한 혜이니의 '콩깍지' 뮤직비디오 촬영현장을 멜론..</a></dd>
<dd class="like_btn" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: right; width: 610px; display: inline-block;">
<p class="left" style="margin: 0px; padding: 3px 0px 0px 1px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; text-align: left;"><span class="colk1_like" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.2em; font-family: 돋움, dotum, 'Apple Gothic', sans-serif; vertical-align: middle;">14</span>&nbsp;<span class="cnt_cmt" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">댓글</span>&nbsp;3</span>&nbsp;<span class="cnt_view" style="margin: 0px 0px 0px 3px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: middle; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #888888;">조회</span>&nbsp;1,489</span></p>
</dd>
</dl>
</div>
</li>
</ul>
</div>
<h3 class="ms_tit" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span class="music_serial" style="margin: 24px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: top; display: inline-block; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bg_h2_title_160712.png') 0px -165px repeat-y; width: 68px; height: 17px;">인기 연재</span></h3>
<div class="wrap_musicserial" style="margin: 12px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<ul class="music_serial_list" style="margin: 0px; padding: 0px; border-width: 1px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: #cccccc initial #cccccc initial; border-style: solid initial solid initial;">
<li class="first_child" style="margin: 0px; padding: 0px; border-top: none; border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none;">
<div class="box_musicserial" style="margin: 0px; padding: 16px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 134px; height: 134px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imageUrl20141229013124.jpg" alt="" width="134" height="134" /></a>
<dl class="info" style="margin: 0px; padding: 19px 0px 0px 22px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 428px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: '맑은 고딕', 'Malgun Gothic', 돋움, Dotum, 'Apple Gothic', sans-serif; vertical-align: baseline; overflow: hidden; height: 20px; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="이슈 포커스">이슈 포커스</a></dt>
<dd class="sumry" style="margin: 0px 0px 11px; padding: 11px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; overflow: hidden; height: 37px; word-wrap: break-word; word-break: break-all;">지금 음악계에는 무슨 일이? 이슈와 트렌드에 따라 모아보는 음악들</a></dd>
<dd class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">연재 : MelOn</span>&nbsp;<span class="subscribe" style="margin: 0px 0px 0px 1px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: inline-block; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;">구독&nbsp;<span style="margin: 0px; padding: 0px; border: 0px; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">10,650</span></span></dd>
</dl>
<div class="musicserial_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; height: 133px; float: right; width: 391px;">
<ul style="margin: -8px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none;">
<li style="margin: 0px; padding: 8px 0px 5px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; overflow: hidden; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 104px; height: 59px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171025051250996.jpg" alt="" width="104" height="59" /></a>
<dl style="margin: 0px; padding: 14px 0px 0px 15px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 259px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; vertical-align: baseline; overflow: hidden; width: 259px; text-overflow: ellipsis; white-space: nowrap;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="다중음격 172회: 대규모 그룹이 성황을 이루기까지 Pt. 1 [한동윤]">다중음격 172회: 대규모 그룹이 성황을 이루기까지 Pt. 1 [한동윤]</a></dt>
<dd class="sumry" style="margin: 4px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">다섯은 평균이 됐다. 예닐곱도 예사다. 이제는 그 이상의 숫자로 구성된 아이돌 그룹이 꾸준히 증가하는 추세다. 세븐틴, 업텐션, 우주소녀, 펜타곤, 바시티, 프리스틴, 굿데이, 골든차일드, TRCNG처럼 열 명 이상의 멤버를 꾸린 팀도 많다. 얼마 뒤에는 12인조 보이 밴드 더보이즈도 데뷔한다. 대가족 그룹은 트렌드나 다름없다.</a></dd>
</dl>
</li>
<li style="margin: 0px; padding: 8px 0px 5px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; overflow: hidden; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 104px; height: 59px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171018051425074.jpg" alt="" width="104" height="59" /></a>
<dl style="margin: 0px; padding: 14px 0px 0px 15px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 259px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; vertical-align: baseline; overflow: hidden; width: 259px; text-overflow: ellipsis; white-space: nowrap;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="다중음격 171회: 고혹적인 목소리의 여성 보컬리스트들 [한동윤]">다중음격 171회: 고혹적인 목소리의 여성 보컬리스트들 [한동윤]</a></dt>
<dd class="sumry" style="margin: 4px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">아무 생각 없이 들었다가 순식간에 넋을 잃게 될지도 모른다. 아직 노래를 듣지 않은 이를 위해 귀띔한다. 마음의 준비를 어느 정도 하는 것이 좋다. 하늘하늘한 목소리가 귓가에 비수처럼 꽂힌다. 그리스 신화 속 세이렌이 따로 없다.</a></dd>
</dl>
</li>
</ul>
</div>
</div>
</li>
<li style="margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;">
<div class="box_musicserial" style="margin: 0px; padding: 16px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 134px; height: 134px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20161128024326.jpg" alt="" width="134" height="134" /></a>
<dl class="info" style="margin: 0px; padding: 19px 0px 0px 22px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 428px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: '맑은 고딕', 'Malgun Gothic', 돋움, Dotum, 'Apple Gothic', sans-serif; vertical-align: baseline; overflow: hidden; height: 20px; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="멜론 스테이지">멜론 스테이지</a></dt>
<dd class="sumry" style="margin: 0px 0px 11px; padding: 11px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; overflow: hidden; height: 37px; word-wrap: break-word; word-break: break-all;">쇼케이스, 콘서트, 내한 공연까지- 현장에서 전하는 생생한 후기와 공연 정보 총집합</a></dd>
<dd class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">연재 : MelOn</span>&nbsp;<span class="subscribe" style="margin: 0px 0px 0px 1px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: inline-block; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;">구독&nbsp;<span style="margin: 0px; padding: 0px; border: 0px; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">2,110</span></span></dd>
</dl>
<div class="musicserial_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; height: 133px; float: right; width: 391px;">
<ul style="margin: -8px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none;">
<li style="margin: 0px; padding: 8px 0px 5px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; overflow: hidden; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 104px; height: 59px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171016115111764.jpg" alt="" width="104" height="59" /></a>
<dl style="margin: 0px; padding: 14px 0px 0px 15px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 259px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; vertical-align: baseline; overflow: hidden; width: 259px; text-overflow: ellipsis; white-space: nowrap;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="올 가을 블랙 뮤직 음악 축제, 2017 서울 소울 페스티벌 ">올 가을 블랙 뮤직 음악 축제, 2017 서울 소울 페스티벌</a></dt>
<dd class="sumry" style="margin: 4px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">2017년 8월 개최 예정이었던 서울소울페스티벌 2017이 아쉽게 연기되고 탄탄한 국내 라인업으로 구성하여 올 11월 다시 찾아온다. 평소 R&amp;B, 힙합, 소울 음악 무대를 기다리던 관객의 기대를 충족시켜줄 예정이다. 음악뿐만이 아닌 블랙 음악이 가지고 있는 문화를 경험할 수 있는 레코드 마켓, 아티스트의 색다른 모습을 만날 수 있는 야외 인터뷰와 싸인회까지 다양한 부대행사로 더욱 풍성한 페스티벌을 예고하고 있다.</a></dd>
</dl>
</li>
<li style="margin: 0px; padding: 8px 0px 5px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; overflow: hidden; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 104px; height: 59px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171013111217951.jpg" alt="" width="104" height="59" /></a>
<dl style="margin: 0px; padding: 14px 0px 0px 15px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 259px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; vertical-align: baseline; overflow: hidden; width: 259px; text-overflow: ellipsis; white-space: nowrap;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="[미화당 라이브] 마음 한 구석에 울림을 선사한 AISLE (아일) 라이브">[미화당 라이브] 마음 한 구석에 울림을 선사한 AISLE (아일) 라이브</a></dt>
<dd class="sumry" style="margin: 4px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">멜론 매거진에서만 접했던 미화당 레코드샵을 실제로 방문하게 되다니! 새로운 뮤지션을 만난다는 부푼 기대감을 안고 조심스레 고개를 숙여 안으로 들어갔습니다. 실내에는 여러 개의 음반 매대를 배경 삼아 악기가 세팅되어 있네요. 동영상 어딘가에서 봤던 기상천외한 장소에서의 다양한 유명 밴드의 공연이 새삼 떠올랐습니다.</a></dd>
</dl>
</li>
</ul>
</div>
</div>
</li>
<li style="margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;">
<div class="box_musicserial" style="margin: 0px; padding: 16px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 134px; height: 134px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20161128120607.jpg" alt="" width="134" height="134" /></a>
<dl class="info" style="margin: 0px; padding: 19px 0px 0px 22px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 428px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: '맑은 고딕', 'Malgun Gothic', 돋움, Dotum, 'Apple Gothic', sans-serif; vertical-align: baseline; overflow: hidden; height: 20px; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="금주의 신보">금주의 신보</a></dt>
<dd class="sumry" style="margin: 0px 0px 11px; padding: 11px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20px; font-family: inherit; vertical-align: baseline;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: block; overflow: hidden; height: 37px; word-wrap: break-word; word-break: break-all;">한 주간 발매된 국내외 신보, 그 중에서 놓쳐선 안될 추천작을 소개해드립니다.</a></dd>
<dd class="" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">연재 : MelOn</span>&nbsp;<span class="subscribe" style="margin: 0px 0px 0px 1px; padding: 0px 0px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; display: inline-block; background: url('http://cdnimg.melon.co.kr/resource/image/web/musicstory/bl_musictoday.jpg') 0px 50% no-repeat;">구독&nbsp;<span style="margin: 0px; padding: 0px; border: 0px; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">4,190</span></span></dd>
</dl>
<div class="musicserial_list" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; height: 133px; float: right; width: 391px;">
<ul style="margin: -8px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none;">
<li style="margin: 0px; padding: 8px 0px 5px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; overflow: hidden; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 104px; height: 59px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171020043757485.jpg" alt="" width="104" height="59" /></a>
<dl style="margin: 0px; padding: 14px 0px 0px 15px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 259px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; vertical-align: baseline; overflow: hidden; width: 259px; text-overflow: ellipsis; white-space: nowrap;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="이 주의 Hidden Tracks : 10월 셋째 주 [DJ히든트랙]">이 주의 Hidden Tracks : 10월 셋째 주 [DJ히든트랙]</a></dt>
<dd class="sumry" style="margin: 4px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">영국 출신의 차세대 싱어송라이터 King Krule과 Kele Okereke, 독창적 트립합 듀오 Scampi부터 친근한 매력으로 어필하는 국내 밴드 큰그림 (Big Picture)까지! 무료한 일상을 특별하게 채워줄 국내외 주요 신보를 이주의 히든트랙과 함께 찾아보세요.</a></dd>
</dl>
</li>
<li style="margin: 0px; padding: 8px 0px 5px; border-width: 1px 0px 0px; border-image: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; list-style: none; overflow: hidden; border-color: #e6e6e6 initial initial initial; border-style: solid initial initial initial;"><a class="thumb" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a; display: inline-block; position: relative; float: left; width: 104px; height: 59px;"><img style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 0px; line-height: 0; font-family: inherit; vertical-align: baseline;" src="http://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20171019031948438.jpg" alt="" width="104" height="59" /></a>
<dl style="margin: 0px; padding: 14px 0px 0px 15px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; float: left; width: 259px;">
<dt style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; vertical-align: baseline; overflow: hidden; width: 259px; text-overflow: ellipsis; white-space: nowrap;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #1a1a1a;" title="위클리 초이스: 10월 셋째 주 [웹진웨이브]">위클리 초이스: 10월 셋째 주 [웹진웨이브]</a></dt>
<dd class="sumry" style="margin: 4px 0px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">한 주간 발표된 수많은 곡들 중 주목할 만한 음악들을 소개하는 코너, 위클리 초이스입니다. 금주는 원더걸스 이후 자기만의 음악세계를 보여주고 있는 핫펠트(예은)와 음악으로 이미지를 만드는 밴드 끝없는잔향속에서우리는, "21세기의 David Bowie"라는 찬사를 받는 St. Vincent의 싱글, 마지막으로 Wanna One 황민현 없이 활동 중인 뉴이스트 W의 앨범을 소개합니다.</a></dd>
</dl>
</li>
</ul>
</div>
</div>
</li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div id="footer" class="my_fold" style="margin: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 12px; line-height: inherit; font-family: 돋움, Dotum, '맑은 고딕', 'Malgun Gothic', 'Apple Gothic', sans-serif; vertical-align: baseline; width: 966px; background-image: url('http://cdnimg.melon.co.kr/resource/image/web/common/bg_footer.jpg'); background-position: initial; background-size: initial; background-repeat: repeat-x; background-attachment: initial; background-origin: initial; background-clip: initial; color: #666666;">
<div class="footer_cont" style="margin: 0px auto; padding: 0px 20px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; width: 1008px; height: auto;">
<div class="footer_menu" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow: hidden;">&nbsp;</div>
</div>
</div>

</div>


<jsp:include page="/WEB-INF/view/footer.jsp" />


</body>
</html>